name: Build do Aplicativo para Windows

on:
  workflow_dispatch: # Permite rodar manualmente pelo site do GitHub

permissions:
  contents: write # Permissão obrigatória para o robô poder criar a página de Release

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código fonte
      uses: actions/checkout@v4

    - name: Configurar o Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Definir Versão Automática
      run: |
        BASE_VERSION=$(mvn -f distribuidora-agua/pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')
        NOVA_VERSAO="$BASE_VERSION.${{ github.run_number }}"
        echo "Gerando versão automatica: $NOVA_VERSAO"
        mvn -f distribuidora-agua/pom.xml versions:set -DnewVersion=$NOVA_VERSAO -DgenerateBackupPoms=false
        echo "APP_VERSION=$NOVA_VERSAO" >> $GITHUB_ENV

    - name: Fazer o Build (Compilar e Gerar o JAR com tudo dentro)
      run: mvn -f distribuidora-agua/pom.xml clean package -Djavafx.platform=win

    - name: Preparar pasta de entrega
      run: |
        mkdir EntregaWindows
        cp distribuidora-agua/target/distribuidora-agua-*.jar EntregaWindows/SistemaLoja.jar
        cp Executavel-Sistema-Loja/INICIAR.bat EntregaWindows/

    - name: Disponibilizar para Download (Artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: Sistema-Loja-Windows-v${{ env.APP_VERSION }}
        path: EntregaWindows/

    - name: Zipar os arquivos para o Release
      run: |
        cd EntregaWindows
        zip -r ../Sistema-Loja-Windows-v${{ env.APP_VERSION }}.zip .
        cd ..

    - name: Criar Release no GitHub
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.APP_VERSION }}
        name: Versão ${{ env.APP_VERSION }}
        files: Sistema-Loja-Windows-v${{ env.APP_VERSION }}.zip
        body: |
          ### Download PRONTO PARA USO (Windows)
          Para rodar o programa, baixe o arquivo `Sistema-Loja-Windows-v${{ env.APP_VERSION }}.zip` logo abaixo em "Assets". 
          Extraia a pasta e dê dois cliques no arquivo **INICIAR.bat**.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
